apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - redis-deployment.yaml
  - vote-deployment.yaml
  - worker-deployment.yaml
  - result-deployment.yaml
  - services.yaml
